### ISSUE TITLE
مشکل عدم نمایش پست های پیشنویس

### ISSUE THREAD

**Issue by khanzadimahdi** [Tarhche/tarhche-website#25]
یه پست ایجاد کردم و پیش نویس گذاشتم وضعیتش رو بعدش ذخیره کردمش اما توی لیست پست ها که میرم نشون نمیده چیزی بهم

**Comment by AliN11** [comment]
@khanzadimahdi فکر نکنم مشکلی داشته باشه. دوباره چک کردی؟
